import pandas as pd
import numpy as np
import streamlit as st
# import spacy
st.header('Audible Book Recomendation')
# nlp = spacy.load('en_core_web_sm')
book_data = pd.read_csv('./audible_book_data.csv')
author_names = book_data['Author'].unique()
author_names = np.insert(author_names, 0, 'all')
tab1, tab2, tab3 = st.tabs(['Book Selection', 'Summary', 'About'])
with tab1:
    feature_names = ['all','audible','absurdist', 'abuse', 'abusive', 'account', 'acting', 'action',
    'active', 'activism', 'activist', 'actor', 'adaptation',
    'addiction', 'administration', 'adolescent', 'adoption', 'adult',
    'adventure', 'adventurer', 'advertising', 'advocacy', 'african',
    'age', 'ageing', 'agnosticism', 'ai', 'allegorical', 'alphabet',
    'alternate', 'alternative', 'amateur', 'america', 'american',
    'amphibian', 'analysis', 'anatomy', 'ancient', 'angel', 'anger',
    'animal', 'anthology', 'anthropology', 'anxiety', 'ape',
    'apologetics', 'archaeology', 'architect', 'architecture', 'area',
    'art', 'artist', 'asia', 'asian', 'aspect', 'astrology',
    'astronomy', 'atheism', 'atmospheric', 'attention', 
    'audiobook', 'audiobooks', 'auditioning', 'author', 'authorship',
    'autobiography', 'autoimmune', 'automation', 'automotive',
    'ballet', 'bank', 'banking', 'baseball', 'bdsm', 'bear', 'bedtime',
    'beginner', 'behaviour', 'behavioural', 'bible', 'biblical', 'big',
    'biographical', 'biography', 'biological', 'biology',
    'biotechnology', 'body', 'bodybuilding', 'book', 'botany', 'boy',
    'brain', 'broadcast', 'buddhism', 'buddhist', 'budgeting', 'bug',
    'bullying', 'business', 'buying', 'campaign', 'canada', 'cancer',
    'capitalism', 'carb', 'care', 'career', 'caribbean', 'castilian',
    'catholicism', 'celebrity', 'central', 'century', 'chakras',
    'change', 'channelling', 'chapter', 'charity', 'chef', 'chemical',
    'child', 'childbirth', 'chinese', 'christian', 'christianity',
    'christmas', 'christology', 'church', 'cinema', 'city', 'civil',
    'civilization', 'class', 'classic', 'classical', 'cleaning',
    'cleansing', 'climate', 'climbing', 'coaching', 'codependency',
    'cognitive', 'cold', 'collar', 'collection', 'college',
    'colonialism', 'comedian', 'comedy', 'comic', 'coming',
    'commentary', 'commerce', 'commercial', 'commodity',
    'communication', 'communism', 'comparative', 'complementary',
    'composer', 'compulsive', 'computer', 'condition', 'conflict',
    'consciousness', 'conservation', 'conservatism', 'conspiracy',
    'constitution', 'consulting', 'consumer', 'contact', 'contagious',
    'contemporary', 'continuing', 'cooking', 'corporate', 'corruption',
    'cosmology', 'cosy', 'counselling', 'craft', 'creativity',
    'creature', 'cricket', 'crime', 'criminology', 'criticism', 'crop',
    'cryptography', 'culinary', 'cult', 'cultural', 'culture',
    'curiosity', 'custom', 'customer', 'cybernetics', 'cyberpunk',
    'cycling', 'dark', 'data', 'database', 'dating', 'death',
    'deception', 'decision', 'deficit', 'democracy', 'demographic',
    'depression', 'design', 'detective', 'detox', 'development',
    'developmental', 'diabetes', 'diary', 'diet', 'diplomacy',
    'direction', 'discipleship', 'discovery', 'discrimination',
    'disease', 'disorder', 'disparity', 'divination', 'divorce',
    'doctrine', 'dog', 'domestic', 'dragon', 'drama', 'dramatisation',
    'dramatization', 'dream', 'dreaming', 'drink', 'dying',
    'dysfunctional', 'dystopian', 'early', 'earth', 'eastern',
    'eating', 'ecology', 'econometrics', 'economic', 'economics',
    'education', 'educational', 'elder', 'election', 'elizabethan',
    'emigration', 'emotion', 'encryption', 'encyclopaedia',
    'encyclopedia', 'engineering', 'english', 'enterprise',
    'entertaining', 'entertainment', 'entrepreneurship', 'environment',
    'environmental', 'environmentalist', 'epic', 'epistemology',
    'epistolary', 'erotic', 'erotica', 'esp', 'espionage', 'essay',
    'estate', 'ethic', 'ethnic', 'etiquette', 'european', 'evangelism',
    'event', 'evolution', 'evolutionary', 'exercise', 'expedition',
    'experience', 'exploration', 'explorer', 'exploring', 'extreme',
    'eye', 'fairy', 'family', 'fantasy', 'farm', 'fascism', 'fashion',
    'fatherhood', 'feeling', 'fiction', 'figure', 'film', 'finance',
    'first', 'fitness', 'flower', 'folk', 'folklore', 'food',
    'football', 'force', 'forecasting', 'foster', 'fox', 'free',
    'freedom', 'french', 'freudian', 'friendship', 'fund', 'future',
    'game', 'gardening', 'gastrointestinal', 'gastronomy', 'gender',
    'genetic', 'genetics', 'genius', 'geography', 'geology',
    'geopolitics', 'german', 'ghost', 'girl', 'globalisation',
    'globalization', 'gothic', 'government', 'graduate', 'grammar',
    'graphic', 'greek', 'green', 'grief', 'growth', 'guide', 'guinea',
    'hamster', 'harassment', 'hard', 'head', 'healing', 'health',
    'healthy', 'higher', 'hindu', 'hinduism', 'historical', 'history',
    'hoax', 'hobby', 'holocaust', 'home', 'homelessness',
    'homeschooling', 'horror', 'house', 'human', 'humanistic', 'humor',
    'humorous', 'humour', 'idea', 'ideology', 'ii', 'illness',
    'immigrant', 'immigration', 'immune', 'imperialism', 'improvement',
    'indian', 'industrial', 'industry', 'infant', 'infertility',
    'inflation', 'injury', 'instruction', 'insurance', 'intelligence',
    'interest', 'interior', 'intermediate', 'international',
    'internet', 'investigator', 'investing', 'investment', 'irish',
    'islam', 'islamic', 'israel', 'issue', 'italian', 'japanese',
    'jewish', 'jogging', 'journal', 'journalism', 'judaism',
    'judicial', 'jungian', 'killer', 'labor', 'labour', 'landscape',
    'language', 'latin', 'latino', 'law', 'leader', 'leadership',
    'learning', 'legal', 'legend', 'leopard', 'lgbt', 'liberalism',
    'liberty', 'life', 'lifestyle', 'light', 'linguistics', 'lion',
    'literary', 'literature', 'living', 'local', 'logic', 'loner',
    'loss', 'love', 'low', 'machine', 'macroeconomics', 'magic',
    'magical', 'maintenance', 'making', 'management', 'marathon',
    'marketing', 'marriage', 'martial', 'mathematics', 'medical',
    'medicine', 'medieval', 'meditation', 'medium', 'meeting',
    'memoir', 'memory', 'mental', 'mentoring', 'metaphysical',
    'metaphysics', 'microeconomics', 'middle', 'military', 'mind',
    'ministry', 'misconduct', 'modern', 'monetary', 'money', 'monkey',
    'monster', 'morality', 'mortgage', 'motherhood', 'motivation',
    'mountaineering', 'mouse', 'movement', 'movie', 'multicultural',
    'murder', 'music', 'musician', 'mutual', 'mystery', 'mysticism',
    'myth', 'mythical', 'mythology', 'native', 'natural', 'naturalist',
    'nature', 'naturopathy', 'need', 'negotiating', 'nervous',
    'network', 'neuropsychology', 'neuroscience', 'new', 'noir',
    'nonfiction', 'norse', 'novel', 'nuclear', 'nursing', 'nutrition',
    'obsessive', 'occult', 'occupational', 'opera', 'option',
    'organisation', 'organisational', 'organised', 'organising',
    'original', 'orphan', 'outcast', 'outdoor', 'outdoors', 'pain',
    'painting', 'palaeontology', 'palestine', 'paranormal',
    'parapsychology', 'parent', 'parenting', 'participation',
    'patient', 'pc', 'performing', 'personal', 'personality', 'pet',
    'pharmacology', 'philanthropy', 'philosopher', 'philosophy',
    'photographer', 'physic', 'physical', 'physician', 'physiology',
    'picture', 'pig', 'planning', 'plant', 'play', 'playwriting',
    'poetry', 'police', 'policy', 'political', 'politician',
    'politics', 'popular', 'pornography', 'postgraduate', 'poverty',
    'power', 'practical', 'practice', 'pregnancy', 'preparation',
    'presentation', 'president', 'primary', 'privacy', 'private',
    'problem', 'procedural', 'process', 'production', 'productivity',
    'professional', 'programme', 'programming', 'project',
    'psychological', 'psychologist', 'psychology', 'psychotherapy',
    'ptsd', 'public', 'publishing', 'quiz', 'quran', 'racism',
    'railroad', 'ranobe', 'reader', 'real', 'realism', 'recovery',
    'reference', 'regency', 'regional', 'rehabilitation',
    'reincarnation', 'relation', 'relationship', 'religion',
    'religious', 'reptile', 'research', 'resolution', 'resource',
    'restaurant', 'retirement', 'revolution', 'right', 'ritual',
    'robotics', 'roman', 'romance', 'romantic', 'rome', 'royalty',
    'runaway', 'running', 'rural', 'russian', 'sacred', 'saga', 'sale',
    'satire', 'scary', 'school', 'science', 'scientist', 'scottish',
    'screenwriting', 'security', 'selling', 'serial', 'sermon',
    'service', 'sex', 'sexual', 'sexuality', 'shakespeare', 'short',
    'sibling', 'skill', 'sleep', 'sleuth', 'small', 'smoking',
    'soccer', 'social', 'socialism', 'society', 'sociology',
    'software', 'solving', 'sorcery', 'southern', 'space', 'spanish',
    'speaking', 'special', 'speech', 'spelling', 'spider', 'spirit',
    'spiritual', 'spiritualism', 'spirituality', 'sport', 'sporting',
    'squirrel', 'standard', 'star', 'state', 'statistic', 'stock',
    'story', 'storytelling', 'strategic', 'strategy', 'stress',
    'stretching', 'structure', 'study', 'style', 'success', 'suicide',
    'superhero', 'supernatural', 'supernaturalism', 'supplement',
    'surveillance', 'survival', 'suspense', 'sustainable', 'sword',
    'system', 'tale', 'taoism', 'tariff', 'teaching', 'technique',
    'technology', 'technothrillers', 'teen', 'teenager', 'tennis',
    'terrorism', 'test', 'testament', 'text', 'textbook', 'theater',
    'theology', 'theory', 'theravada', 'thought', 'thriller',
    'tibetan', 'tiger', 'time', 'tobacco', 'toddler', 'tool',
    'tourism', 'town', 'toy', 'trade', 'trading', 'tradition',
    'traditional', 'training', 'transportation', 'travel', 'tree',
    'triathlon', 'true', 'tudor', 'tv', 'unexplained', 'united',
    'university', 'urban', 'verse', 'video', 'vigilante', 'violence',
    'vision', 'visionary', 'vitamin', 'vocabulary', 'war', 'warfare',
    'weight', 'weightlifting', 'wellness', 'welsh', 'white', 'wicca',
    'witchcraft', 'wolf', 'woman', 'word', 'work', 'workout',
    'workplace', 'world', 'writing', 'yoga', 'young', 'zen']
    
    genre_list = ['all', 'Small Businesses', 'Folk Tales & Myths for Children','White Collar & Corporate True Crime',
    'Education Parent Participation', 'Cancer',
    'Study of Customs & Traditions',
    'Paranormal Romance',
    'Encyclopaedias & Reference Works ',
    'Horror Fiction',
    'Alternative & Complementary Medicine',
    'Words',
    'Wicca',
    'Banks & Banking ',
    'LGBT Biographies',
    'Film History & Criticism',
    'Southern United States Literature',
    'Freudian Theory',
    'Eating Disorders',
    'Cooking',
    'Higher & Continuing Education',
    'Naturopathy',
    'French Literature',
    'Power Resource Engineering',
    'Social Work',
    'Divorce',
    'Twelve-Step Programmes',
    'Cyberpunk Science Fiction',
    'Unexplained Mysteries',
    'Fitness Workouts',
    'Epic Fantasy for Teens',
    'Art Instruction & Technique',
    'Anthologies ',
    'Romance ',
    'Asian History for Children',
    "Children's Religion ",
    'Globalisation',
    'Contemporary Romance ',
    'Literary Theory',
    'Military History ',
    "Children's Studies Social Science",
    'Literary Fiction for Teens',
    'Public Finance ',
    'Time Travel Fiction for Teens',
    'Evolution',
    'Fantasy Movie',
    'Literary History & Criticism',
    'Historical Mysteries',
    'Church & State',
    'Environmental Conservation',
    'Philosophy & Science',
    'Human Geography',
    'Islam ',
    'Supernaturalism',
    'Erotic Fiction',
    'Drink & Entertaining ',
    'Marriage',
    'Animal Action & Adventure for Children',
    'Grief & Loss',
    'Nonfiction on Emotions & Feelings for Children',
    'Anthropology ',
    'Educational Psychology',
    'True Crime',
    'Labor & Industrial Relations',
    'Biographies of Celebrities & Entertainment Professionals',
    'Homeschooling',
    'Investing & Trading Options',
    'Exploring Asia Fiction for Children',
    'Paranormal Romance for Teens',
    'Humanistic Psychology',
    'Literature & Fiction ',
    'Classic Fiction ',
    'Hindu Rituals & Practices',
    'History & Criticism',
    'Sports Romance',
    'Classic Literature',
    'Addiction & Recovery',
    'English History',
    'Humorous Fiction for Children',
    'Entrepreneurship ',
    'Time Management',
    'Society & Social Sciences',
    'Christian Classic & Allegorical Fiction',
    'Geology',
    'Social Sciences ',
    'Dystopian Fiction for Teens',
    'Ethnic & Regional Biographies',
    'Mysteries for Children',
    'Psychology Movements',
    'Jewish Literature',
    'Fiction on Death & Dying for Teens',
    'Economic History ',
    'Social Classes & Economic Disparity',
    'European History ',
    'Agnosticism ',
    "Children's Science Fiction ",
    'Business Consulting',
    'Stress Management',
    'Friendship Fiction',
    'Science Fiction for Teens',
    'Mystery & Detective Fiction for Teens',
    'International Business ',
    'Biographies of Presidents & Heads of State',
    'Fatherhood',
    'Guinea Pigs & Squirrels Fiction for Children',
    'Alphabet Reference',
    'Fiction on Mental Illness for Teens',
    'Christmas Fiction for Children',
    'Retirement Planning',
    'Small Town & Rural Fiction',
    'Technology & Medicine ',
    'Humorous Fiction',
    'History of Civilization & Culture',
    'Amateur Sleuth Mysteries',
    'TV & Video Game Tie-ins for Teens',
    'United States History for Children',
    'Developmental Psychology ',
    'Diabetes Diets',
    'Christian Sermons',
    'Contagious Diseases',
    'Business Writing',
    'Biographical Fiction',
    'Sustainable & Green Living',
    'Terrorism',
    'Anger Management',
    'Motherhood',
    'Biographies',
    'Scottish & Welsh Literature',
    'Communism & Socialism',
    'Zen Buddhism',
    'Creativity',
    'Political Fiction',
    'LGBT Thrillers & Suspense',
    'Sociology of Urban Areas',
    'Budgeting',
    'History of the Americas',
    'Foxes & Wolves Fiction for Children',
    'Action & Adventure Mysteries for Children',
    'Smoking & Tobacco',
    'Philosopher Biographies',
    'Dystopian Science Fiction',
    "Children's Health",
    'Design & Fashion ',
    'Politics',
    'French Language Learning',
    'History of Ideas',
    'Writing Guides ',
    'Magical Realism Fiction',
    'Christian Theology',
    'Sword & Sorcery Fantasy',
    'Hindu Biographies',
    'Romance Anthologies & Short Stories',
    'Healthy Living & Wellness',
    'Angels & Spirit Guides',
    'Legends & Sagas',
    'Political Biographies for Children',
    'Contemporary Fantasy for Teens',
    'Audiobooks on Siblings for Teens',
    'Environmental Economics ',
    'Vocabulary',
    'Law Biographies',
    'Urban Fantasy',
    'Nature & Ecology',
    'Military Strategy',
    'Ecology ',
    'Capitalism',
    'Ghost Horror Fiction',
    'Extreme Sports',
    'Gardening & Landscape Design',
    'Parenting School-Age Children',
    'Computer Science ',
    'Divination',
    'Dark Humour Literature & Fiction',
    'Fantasy Romance for Teens',
    'Mental Health ',
    'Business Decision Making & Problem Solving',
    'Post-Apocalyptic Science Fiction',
    'Science',
    "Children's Horror & Ghost Stories ",
    'Anthologies & Short Stories for Children',
    'Meditation ',
    'Fiction on Girls for Children',
    'Logic & Language Philosophy',
    'Social Scientist & Psychologist Biographies',
    'Commerce',
    'Fairy Tale Collections & Anthologies for Children',
    'Political Freedom & Security ',
    'International Relations & Globalization',
    'Hindu Sacred Writings',
    'E-Commerce',
    'Atheism ',
    'Network Administration',
    'Business Development ',
    'Personality Disorders',
    'Religion & Sociology',
    'Eastern Philosophy',
    'Myths',
    'Machine Theory & AI',
    'Ancient History ',
    'Transportation & Automotive ',
    'Criminology ',
    'Gastronomy',
    'Active & Outdoor',
    'Practices & Sacred Texts',
    'Serial Killers True Crime',
    'English',
    'Fairy Tale Fantasy',
    'German Language Learning',
    'Mortgages',
    'LGBT Romance',
    'Insurance',
    'Survival Stories for Teens',
    'Stocks',
    'Crime Fiction for Teens',
    'Playwriting',
    'Paranormal Fantasy',
    'Hoax & Deception True Crime',
    'Historical Fiction ',
    'Atmospheric Sciences',
    'Science Fiction Movie',
    'Free Audible Audiobooks & Originals ',
    'Women Business',
    'Biology ',
    'Free Enterprise',
    'Writing',
    'Mental & Spiritual Healing',
    'Evolutionary Psychology',
    'Christian Ministry & Evangelism',
    "Children's Literature & Fiction ",
    'Diaries & Journals',
    'Animal Fiction',
    'Time Management & Productivity',
    'Political Philosophy',
    'Technology & Society',
    'Epistemology ',
    'Space Exploration Science Fiction',
    'Organised Crime',
    'Fiction on Parents for Children',
    'Commercial Real Estate',
    'Privacy & Surveillance Studies',
    'Bears Fiction for Children',
    'Mysticism ',
    'Painting ',
    'Love & Romance',
    'Israel & Palestine History',
    'Business & Careers',
    'Conservatism & Liberalism',
    "Children's Sport ",
    'Fairy Tale Adaptations for Children',
    'Action & Adventure ',
    'Christian Evangelism',
    'Engineering & Technology ',
    'Superhero Fantasy',
    'Linguistics ',
    'Computer Programming Language & Tool',
    'Fiction on Family for Teens',
    'Asian History ',
    'Injuries & Rehabilitation',
    'Civil Rights & Liberties',
    'Natural History',
    'Theology & Philosophy of Religion',
    'Ancient & Classical Literature Collections',
    'Biblical Fiction',
    'Reincarnation ',
    'Lifestyle & Personal Style Guides ',
    'TV & Video Game Tie-Ins for Teens',
    'Graphic Design',
    'Sports Fiction for Children',
    'Obsessive Compulsive Disorder',
    'Money & Monetary Policy',
    'Music Books',
    'inth Century Historical Romance',
    'Computer Security & Encryption',
    'Software Development & Engineering',
    'Hinduism for Children',
    'Literary Essays',
    'Cognitive Behavioural Psychology',
    'History of Religion ',
    'Botany & Plants',
    'Romantic Comedy for Teens',
    'Sleep Disorders',
    'Native American History',
    'Religious & Spiritual Fiction',
    'Adventurers & Explorers for Children',
    'Modern Philosophy',
    'Computer Programming Languages',
    'Infertility',
    'War & Military Fiction',
    'Absurdist Fiction',
    'Film & TV',
    'Interest',
    'Study Guides & Test Preparation',
    'Environment ',
    'Cryptography',
    'Adventurers',
    'Biographies & Autobiographies ',
    'Long-Term & Elder Care',
    'Women Biographies',
    'Counselling & Psychotherapy',
    'Nonfiction on Friendship for Children',
    'Military & War Biographies',
    'Spelling Reference',
    'Italian History',
    'Textbooks & Study Guides',
    'Fantasy Romance',
    'Science Fiction ',
    'Latino American Literature',
    'Drama & Plays ',
    'Running & Jogging',
    'Contemporary Fantasy',
    'Attention Deficit Disorders',
    "Children's Humour ",
    'Sci-Fi Movie',
    'Low Carb Diets',
    'Islamic Biographies',
    'Customer Service',
    'Ageing Health',
    'Sporting Events & Organisations ',
    'Neuroscience & Neuropsychology',
    'Folklore & Mythology Studies',
    'Science Fiction Dramatisations',
    'Metaphysical & Visionary Fiction',
    'Corporate Finance',
    'Fiction on Illness & Health Problems for Teens',
    'Social Theory',
    "Children's Family",
    'Apes & Monkeys Fiction for Children',
    'City Life Fiction',
    'Software Architecture',
    'Asia Politics & Government',
    'Physician & Patient ',
    'Alternate History Science Fiction',
    'Metaphysics ',
    'Study Guides',
    'Parapsychology',
    'Yoga ',
    'Mutual Funds',
    'Project Management',
    'Fantasy Dramatisations',
    'Theology ',
    'Contemporary Fiction ',
    'Internet & Social Media ',
    'Superhero Fiction for Teens',
    'Parent & Adult Children Relationships',
    'Traditional Detective Mysteries',
    'Biographies of Actors',
    'Greek & Roman Fairy Tales for Children',
    'Christian Thriller & Suspense',
    'Bugs & Spiders Fiction for Children',
    'German History',
    'PaManagement',
    'Spirituality ',
    'History ',
    'Fiction on Adoption for Children',
    'Reptiles & Amphibians Fiction for Children',
    'Dragon & Mythical Creatures Fantasy',
    'History of Technology',
    'Pornography Studies',
    'Comparative Religion',
    'Games & Quizzes ',
    'Personal Success Business',
    'Military Thrillers',
    'Adult & Continuing Education',
    'Action & Adventure Fantasy for Children',
    'Sustainable Development',
    'LGBT Historical Fiction',
    'Vigilante Fiction',
    'Paranormal & Supernatural Fiction for Teens',
    "Children's Reference ",
    'Politics & Government',
    'Fiction on Bullying for Children',
    'Paranormal & Supernatural Fantasy for Children',
    'Physical Illness & Disease',
    'Nutrition & Healthy Eating',
    'Asia Travel & Tourism',
    'Technothrillers',
    'Contemporary Romance for Teens',
    'Indian Literature ',
    'Christology',
    'Money & Finance',
    'Poetry ',
    'Survival Stories for Children',
    'Business & Economics',
    'Private Investigator Mysteries',
    'Pigs Fiction for Children',
    'True Accounts ',
    'Dragons & Mythical Creatures Fantasy for Children',
    'Buying & Selling Homes',
    'Audiobooks on Bedtime & Dreaming for Children',
    'Classic Action & Adventure',
    'Diets',
    'Memory Improvement',
    'Biological & Chemical Warfare',
    'Taoism',
    'International Economics',
    'Data Science',
    'Revolution Histories',
    'Space Opera Sci-Fi for Teens',
    'War & Military Action Fiction',
    'Christian Spiritual Growth',
    'World History ',
    'Caribbean & LatAmerican Literature',
    'Medieval European History',
    'Sciences',
    'Acting & Auditioning',
    'Mystery Action Fiction',
    'United States Politics & Government',
    'Spanish Language Learning',
    'Suspense',
    'Adventure Travel',
    'Communication & Social Skills',
    'New Thought Spirituality',
    'Parenting Special Needs Children',
    'Language Learning & Teaching',
    'Research & Publishing Guides',
    'Military Intelligence & Espionage',
    'Parenting Infants & Toddlers',
    'History of Science',
    'Mystery Anthologies & Short Stories',
    'Biographies of Religious Figures',
    'Earth Sciences ',
    'Adult Collections & Anthologies',
    'Poverty & Homelessness Studies',
    "Children's Science",
    'Econometrics & Statistics',
    'Christian Marriage & Relationships',
    'Crop Science',
    'Theater & Ballet',
    'Nursing ',
    'Family Life Fiction',
    'Christian Romance',
    'Popular Culture Studies',
    'Diabetes',
    'Religion & Spirituality ',
    'Industrial Engineering ',
    'Time Travel Science Fiction',
    'Cleaning & Organising',
    'Soccer ',
    'Adolescent Psychology',
    'Investing & Trading',
    'Christianity ',
    'Light Novels  for Teens',
    'Christian Family',
    'Classical & Medieval Poetry',
    'African American Literature',
    'Intelligence & Espionage',
    'United States History ',
    'Public Relations',
    'Gothic Horror Fiction',
    'Native American Demographic Studies',
    'US State & Local History',
    'Women Biographies for Children',
    'Epic Poetry',
    'Supernatural Thrillers',
    'Mentoring & Coaching',
    'World Literature ',
    'Explorers & Survival Biographies',
    'Nonfiction Intermediate Readers for Children',
    'Triathlon ',
    'Sports & Outdoors ',
    'Biographies of Royalty',
    'Gardening Techniques',
    'Marathon & Running',
    'Romance for Teens',
    'Witchcraft',
    'Environmentalists & Naturalists Biographies',
    'Satire Fiction',
    'Paranormal Fantasy for Teens',
    'Fiction on Violence for Children',
    'Consumer Behaviour',
    'Public Speaking',
    'Cosmology',
    'Real Estate Investments',
    'LGBT Literature & Fiction for Teens',
    'Theory & Criticism',
    'Political Advocacy & Activism',
    'Biology Books',
    'Central Asian History',
    'Historical Romance ',
    'Business Sales',
    'Neuro-Linguistic Programming',
    'Leadership',
    'Conflict Resolution',
    'Crime Action Fiction',
    'Biographies of Politicians',
    'Music Instruction & Technique',
    'Databases & Big Data',
    'Special Forces Military History',
    'Political Campaigns & Elections',
    'Astrology ',
    'Family Life Fiction for Children',
    'Astronomy ',
    'Spiritualism',
    'Speech',
    'Audiobooks on Diseases for Children',
    'Immune Systems & Autoimmune Diseases',
    'Religion For Children',
    'Computers & Internet',
    'Animals',
    'Crime',
    'Home & House Maintenance',
    'Southern African History',
    'Business Management',
    'Conflict Management',
    'Occult Horror Fiction',
    'Epic Fantasy',
    'Literature Anthologies',
    'Thriller & Suspense Stories for Children',
    'International Diplomacy',
    'Relationships',
    'Railroad Engineering',
    'Compulsive Disorders',
    'Historical Fiction for Teens',
    'Action & Adventure Fiction for Teens',
    'Spirituality of Dreams',
    'History of Exploration for Children',
    'Exploring United States Nonfiction for Children',
    'Science Fiction Romance for Teens',
    'Tudor & Elizabethan History',
    'Comedy ',
    'Railroad Travel',
    'Fiction Classics for Children',
    'Consciousness & Thought',
    'Biographies of Activists',
    'Historical Thrillers',
    'Action Thriller Fiction',
    'Spiritual Channelling',
    'Rome',
    'Public Speaking Reference',
    'Audiobook Beginner Readers for Children',
    'Fantasy ',
    'Russian History',
    'Cinema & Broadcast ',
    'Humorous Fantasy',
    'Depression',
    'Programming',
    'Movie',
    'Fiction on Orphans & Foster Homes for Children',
    'United States Literature',
    'Audiobooks on Health for Children',
    'Biographies of Comedians',
    'Thrillers & Suspense for Teens',
    'Genetics ',
    'Labour & Industrial Relations',
    'Regency Romance',
    'Fiction on Racism & Discrimination for Teens',
    'Audible Audiobooks & Originals ',
    'History of Christianity',
    'Graphics & Design',
    'Psychology ',
    'Fascism',
    'Globalisation Money & Finance',
    "Children's Traditional Stories ",
    'Audiobooks on Family Life for Children',
    'Medicine History & Commentary',
    'Special Education ',
    'Tibetan Buddhism',
    'Noir Fiction',
    'Diaries & True Accounts',
    'Industries',
    'Psychological Fiction',
    'Political Science ',
    'Study Skills',
    'Genetic Diseases',
    'Philosophy History',
    'Sociology of Death & Dying',
    'Irish',
    'Physics ',
    'Christian Discipleship',
    'Weight Loss Diets',
    ',Standard French',
    'Historical Fantasy',
    'Literature & Fiction for Children',
    'Stories About Toys for Children',
    'First Contact Science Fiction',
    'Early Learning Audiobooks for Children',
    'Graduate School Test Preparation',
    'Primary Education',
    'Philosophy ',
    'Horror ',
    'Plays',
    'Stories Verse for Children',
    'Inflation',
    'TV & Video Game Tie-Ins',
    "Women's Christian Living",
    'Lions',
    'Sociology ',
    'Historical Biographies',
    'Nonfiction Chapter Books for Children',
    'History of Civilization',
    'Authorship',
    'Self-Hypnosis',
    'star',
    "Children's Action & Adventure",
    'Economic Theory ',
    'Archaeology ',
    'PTSD',
    'Fitness Stretching',
    'Business Communication ',
    'Personal & Social Issues ',
    'Economics ',
    'Climbing & Mountaineering ',
    'Analysis & Strategy',
    'Essays ',
    'Geopolitics',
    'Culinary Biographies',
    'Personal Development',
    'Art for Teens',
    'New Business Enterprises',
    'Cycling ',
    'Dogs & Dog Care',
    'Other Religions',
    'Personal Finance',
    'Computer Science Books',
    'Pets Fiction for Children',
    'Abusive Relationships',
    'Mystery Dramatizations',
    'Sports ',
    'Fantasy for Teens',
    'Humour',
    'Pets & Animal Care ',
    'Art of Storytelling',
    'Multicultural Fiction for Teens',
    'Myths & Legends for Teens',
    'Racism & Discrimination Studies',
    'Biographies of Science & Technology Leaders',
    'African American History',
    'Celebrity Chefs & Restaurants',
    'Language',
    'Sex Instruction',
    'Cybernetics',
    'Art History & Criticism',
    'Dark Fantasy',
    'Mythology & Folklore Encyclopedias',
    'Exercise & Fitness ',
    'Religious Cults',
    'Colonialism & Post-Colonialism',
    'Jungian Psychology',
    'Negotiating',
    'Human Rights',
    'Workplace Culture',
    'Real Estate Investing & Finance',
    'Historical Fiction for Children',
    'Ancient & Classical Roman History',
    'Macroeconomics ',
    'Nature & Technology ',
    'History & Culture for Teens',
    'Action & Adventure for Children',
    'Non-Profits & Charities',
    'Farm Animals Fiction for Children',
    'Espionage Thrillers',
    'Crime Fiction',
    'PC & Video Games ',
    'Forecasting & Strategic Planning',
    'Multicultural Romance',
    'Elections & Political Process',
    'Postgraduate School Education',
    'Comparative Political Science',
    'Entertainment & Performing Arts Business Aspects',
    'Mysteries',
    'Language & Grammar ',
    'Education ',
    'Martial Arts ',
    'History of Judaism',
    'Women Sleuth Mysteries',
    'Sexual Addiction',
    'Vision & Eye Problems',
    'Action & Adventure Fantasy for Teens',
    'Religious History',
    'Domestic Thrillers',
    'United States Immigrant History',
    'History of Hinduism',
    'Buddhist Sacred Writings',
    'College & University Test Preparation',
    "Women's Fiction",
    'Middle Eastern History ',
    'Religion & Philosophy',
    'Biotechnology',
    'Political Theory',
    'Expeditions & Discoveries ',
    'Psychological Thrillers',
    "Children's Crime & Thriller ",
    'Cleansing & Detox Diets',
    'Dogs Fiction for Children',
    'Marketing ',
    'Screenwriting',
    'Women History',
    'Creativity & Genius',
    'Literary Criticism for Children',
    'Hard-Boiled Mysteries',
    'Philosophy of Society',
    'Society & Culture ',
    'Journalism Books',
    'Exploring the World for Children',
    'Fiction on Friendship for Children',
    'Football ',
    'Biographies of Authors',
    'Christian Apologetics',
    'Economic Conditions ',
    'Cultural',
    'Cold War',
    'Animal Fiction for Children',
    "Children's History ",
    'Imperialism',
    'Philanthropy & Charity',
    'Investing & Trading Commodities',
    'Investing Analysis & Strategy',
    'Body & Spirit',
    'Quran',
    'Environmental Public Policy',
    'Child Psychology',
    'Tigers & Leopards Fiction for Children',
    'Democracy',
    'Fiction on Dating & Sex for Teens',
    'Fairy Tales',
    'Monster Stories for Children',
    'Advertising',
    'Business Ethics ',
    'Violence Society',
    'Biological Sciences',
    'International Relations ',
    'Humor for Children',
    'Earth Sciences Books',
    'Bibles',
    'Etiquette Guides',
    'Bra& Nervous System Diseases',
    'Hard Science Fiction',
    'Emotions',
    'Teen & Young Adult',
    'Political Science History & Theory',
    'Biographies of Business Leaders',
    'English Language Learning',
    'Microeconomics ',
    'Murder True Crime',
    'Out-of-Body Experiences',
    'Gender Issues',
    'Crime Thrillers',
    'Mice',
    'Action & Adventure Anthologies & Short Stories',
    'Conspiracy Thrillers',
    'Hinduism ',
    'Epistolary Fiction',
    'Occult & Paranormal',
    'World War II Historical Fiction',
    'Economic Public Policy',
    'Greek & Roman Philosophy',
    "Children's Picture Books ",
    'Parenting',
    'Business Careers',
    'Medical Biographies',
    'Palaeontology',
    'Russian Literature',
    'Christian Death & Grief',
    'Political Thrillers',
    'International Trades & Tariffs',
    'Pharmacology ',
    'Fantasy & Magic for Children',
    'Law ',
    'Nuclear Warfare',
    'Emigration & Immigration Studies',
    'Asian Literature ',
    'Religious Ethics',
    'Human Sexuality Psychology',
    'Architecture ',
    ',Standard Italian',
    'Bible Study Guides',
    'Horror Fiction for Teens',
    'Anxiety Disorders',
    'Fiction on Suicide for Teens',
    'Bodybuilding & Weightlifting',
    'Fiction on Runaways for Teens',
    'Scary Stories for Children',
    'Science Fiction Anthologies & Short Stories',
    'Historical Biographies for Children',
    'Theravada Buddhism',
    'Biographies & Memoirs ',
    'Automation & Robotics',
    'Money Management',
    'Hamsters',
    'Fiction on Loners & Outcasts for Teens',
    'Computer Security',
    'TV & Video Game Tie-In Fiction',
    'Literary Fiction',
    'LGBT Studies',
    'Urban Fiction',
    'Ancient Historical Fiction for Children',
    'Catholicism',
    'Chakras',
    'World War II History',
    'Coming of Age Fiction',
    'Sports Biographies',
    'New Testament Bible Study',
    'Codependency',
    'Cosy Mysteries',
    "Children's Fantasy ",
    'Ancient',
    'Mind',
    'Vocabulary Books',
    'Film Direction & Production',
    'Space Opera Science Fiction',
    'Medical Ethics ',
    'Erotic Romance',
    'Personal Development & Self-Help',
    "Children's Mysteries & Curiosities ",
    'African American Demographic Studies',
    'Fairy Tales for Teens',
    'Political Corruption & Misconduct',
    'Short Stories ',
    'Tennis ',
    'Food',
    'Travel Writing ',
    'Action & Adventure Fiction',
    'Interior Design',
    'Fiction on Friendship for Teens',
    'Indian History ',
    'Sports Fiction',
    'Economics Books',
    'Dramatisations',
    'Audiobooks on Law & Crime for Children',
    'Vitamins & Supplements',
    'Action & Adventure Fantasy',
    'Fiction on Racism & Discrimination for Children',
    'Thrillers & Suspense',
    'Fiction Sagas',
    'Adventure Science Fiction',
    'Fiction on Siblings for Children',
    'Romantic Comedy',
    'Sports Training & Coaching ',
    'Military Science',
    'Baseball ',
    'Pregnancy & Childbirth',
    'Judicial Systems',
    'Linguistics & Writing ',
    'Cricket ',
    'Coaching',
    'Law History',
    'Art',
    'Future Studies',
    'Military Fantasy',
    'Buddhism ',
    'Public Health ',
    'Legal Thrillers',
    'Buddhist Philosophy & Practice',
    "Children's Comics & Graphic Novels",
    'Occupational & Organisational Psychology',
    'Anatomy & Physiology ',
    'Literature & Fiction for Teens',
    'Travel & Tourism ',
    'Sociology of Sports',
    'Self-Esteem',
    'C Programming Language',
    'Audiobooks on Flowers & Trees for Children',
    'Political Structure & Processes',
    'Family & Relationships',
    'Media Studies ',
    'Fiction on Boys for Children',
    'Outdoor Survival Skills ',
    'Business Etiquette',
    'Dysfunctional Family Relationships',
    'Sexual Abuse & Harassment',
    'Norse Fairy Tales for Children',
    'Gastrointestinal Diseases',
    'Police Procedural Mysteries',
    'Chinese History',
    'Personal Success',
    'Organisational Behaviour',
    'Climate Change',
    'Thriller & Suspense Dramatizations',
    'History of Psychology',
    'Time Travel Science Fiction for Children',
    'Fiction Short Stories',
    'Judaism ',
    'Historical Fantasy for Teens',
    'Thriller & Mystery ',
    'Fiction on Depression for Teens',
    'Language Learning',
    'Social Media',
    'Romantic Suspense ',
    'Political Ideologies & Doctrines',
    'Sports Psychology',
    'Holocaust',
    'Mathematics ',
    'International Mystery & Crime',
    'Animals for Children',
    'Theory & Philosophy',
    'Meetings & Presentations',
    'Parenting Teenagers',
    'Ethics & Morality Philosophy',
    'Biographies of Composers & Musicians',
    "Women's Studies",
    'Historical Action & Adventure for Children',
    'Philosophy Movements',
    'Business Motivation & Self-Improvement',
    'Social Psychology',
    'Travel Writing & Commentary'
    ]
    # tips = ["Search 'Free' to list the free audiobooks in Genre Option or sort the price in ascending order", 
            # "Results are based on Genre. You can search with keyword like 'Crime', 'Thriller', 'Romance' for better results",
            # "Select 'All' to list all available books", 
            # "Check recomendation for more related books", 
            # 'Use Deep Search to for More results',
            # "If Price is 0, it's Free. Sort Books by Price to view all Free Books", 
            # 'Select 0 rating to see unrated books. You may find some Hidden gems. Check "Flow: Living at the Peak of Your Abilities" book for instance']
    
    
    book_name = ""
    # with st.sidebar:
    e1, e2 = st.columns(2)
    
    with e1:
        st.subheader(f'Total Availabe Books: {book_data.shape[0]}')
        search_option = st.radio('Search Option',['Book Name', 'Genre', 'Author'], horizontal=True )
        recomend_option = st.radio('Recomendation Option', ['Genre', 'Global'], 
                                help = 'Global Recomendation will be based on book description', horizontal=True )
        book_rating = st.number_input('Select Rating', min_value = 0, max_value = 5, step = 1)
        deep_search = st.checkbox('Deep Search', 'Deep Search', help = 'Search keyword in Genre and Book Description')
        
    with e2:
        # i = np.random.randint(0, 7)
        # st.write(f'Tip: {tips[i]}')
        if search_option == 'Genre':
            # genre = st.selectbox('Search', feature_names, index = 0, placeholder = 'Search')
            genre = st.selectbox('Search', genre_list, index = 0, placeholder = 'Search')
        elif search_option == 'Author':
            author_search = st.selectbox('Search', author_names, index = 0, placeholder = 'Search')
            # author_name = st.text_input('Author Name', placeholder='Search by Author Name', label_visibility='hidden')
        else:
            book_search = st.text_input('Search', placeholder='Search')      
    if book_rating < 1:
        rating = -1
    else:
        rating = book_rating
    # d1, d2, = st.columns([1, 2])
    # with d1:
    #     # search_option = st.radio('Search Option',['Book Name', 'Genre', 'Author'] )
    #         None
    # with d2: 
    #     # if search_option == 'Book Name':
    #     #     book_name = st.text_input('Book name', placeholder='Search by Book Name', label_visibility='hidden')
            
    #     # if book_name == "":
        
    st.divider()        
    # dataframe creation after the search option is selected.
    if search_option == 'Book Name':    
        book_name = book_search
        df1 = book_data[book_data['Book Name'].str.contains(book_name, case = False)]
    elif search_option == 'Author':
        author_name = author_search
        if author_search == 'all':
            df1 = book_data[book_data['Rating'] >= rating]
        else:
            df1 = book_data[book_data['Author'].str.contains(author_name, case = False)]
    else:
        if genre == 'all':
            df1 = book_data[book_data['Rating'] >= rating]
        else:
            if deep_search == False:
                df1 = book_data[(book_data['Ranks and Genre'].str.contains(genre, case = False)) & (book_data['Rating'] >= rating)]
            else:
                df1 = book_data[((book_data['Ranks and Genre'].str.contains(genre, case = False)) | 
                                    (book_data['Description'].str.contains(genre, case = False))) 
                                    & (book_data['Rating'] >= rating)]
    
    #search Results
    st.write('\n')
    st.subheader('\n Results')
    # c3, c4 = st.columns([3,1])
    # with c3:
        
    st.write(f'{df1.shape[0]} Books')
    event = st.dataframe(
                        data=df1[['Book Name', 'Author', 'Rating', 'Price', 'Genre', 'Genre_Cluster_1', 'Clusters2']],
                        # key = 'data', 
                        use_container_width=True,
                        on_select ='rerun', 
                        hide_index = True,
                        column_order=['Book Name', 'Author', 'Rating', 'Price', 'Genre'],
                        selection_mode="single-row",
                        )
    books = event.selection
        #books
    if books:
        filtered_book = df1.iloc[books.rows]
        description = st.dataframe(filtered_book['Description'], hide_index=True, use_container_width=True)
    # with c4:
    #     st.table(filtered_book['Genre'])
        
    try:    
        #recomendation Option Selection
        if recomend_option == 'Global':
            cluster = int(df1.iloc[books.rows]['Clusters2'])
            recomended_books = book_data[book_data['Clusters2'] == cluster][['Book Name', 'Author', 'Rating','Description', 'Genre', 'Price']]
        else:
            cluster = int(df1.iloc[books.rows]['Genre_Cluster_2'])
            recomended_books = book_data[book_data['Genre_Cluster_2'] == cluster][['Book Name', 'Author', 'Rating','Description', 'Genre','Price']]
        
        st.write(int(cluster))
        st.markdown('### :blue[Recomended Books based on your Selection]')
        
        #selecting recomended books
        st.write(f'{recomended_books.shape[0]} recomendations')
        # col3, col4 = st.columns([3, 1])
        # with col3:
        recomendations = st.dataframe(recomended_books,
                    hide_index=True,
                    use_container_width=True,
                    column_order=['Book Name', 'Author', 'Rating', 'Price', 'Genre'],
                    on_select='rerun',
                    selection_mode='single-row')
        
        recomend_index = recomendations.selection.rows
        recomended_selection =recomended_books['Description'].iloc[recomend_index]
        st.dataframe(recomended_selection, hide_index=True, use_container_width=True)
        
        # st.dataframe(recomended_selection.style.hide(axis = "index"))
        
        
        # with col4:
        #     #display recomended book description
                
        #         recomended_genre = st.table(recomended_books['Genre'].iloc[recomend_index])
    except (NameError, TypeError) as e:
        pass
    
    try:
        # col5, col6 = st.columns([3,1])
        # with col5:
        author = ''
        author_select = recomended_books.iloc[recomend_index]['Author'].to_string()
        author_select = author_select.split(" ")
        author = " ".join(author_select[4:])
        st.markdown(f''':orange[More Books by {author}]''')
        
        author_lib = book_data[book_data['Author'] == author]
        
        author_cluster = st.dataframe(data = author_lib,
                            column_order=['Book Name', 'Rating', 'Price', 'Genre', 'Description'],
                            on_select='rerun',
                            selection_mode='single-row')
        author_index = author_cluster.selection.rows
        description_book_author = st.dataframe(author_lib['Description'].iloc[author_index], hide_index=True, use_container_width=True)
        # with col6:
        # genre_author = st.table(author_lib['Genre'].iloc[author_index])
    except NameError:
        pass
    
with tab2:
    # st.bar_chart(df1, x = 'Book Name', y = 'Rating')
    # st.line_chart(df1, x = 'Book Name', y = 'Price')
    # st.bar_chart(df1, x = 'Price', y = 'Rating')
    # st.scatter_chart(df1, x = 'Rating', y = 'Price')
    insight_selection = st.radio('Check Insight', ['By Rating', 'By Author', 'By Reviews'])
    if insight_selection == 'By Rating':
        rating_data0 = book_data.groupby('Rating')['Price'].mean()
        st.scatter_chart(data = book_data, y = 'Price', x = 'Rating')
        st.bar_chart(rating_data0, y = 'Price', x_label='Rating', y_label = 'Average Price' )
    elif insight_selection == 'By Author':
        e1, e2 = st.columns(2)
        with e1:
            order_selection = st.selectbox('', ['Top', 'Bottom'])
        with e2:
            n = st.number_input('Enter Number of Authors', min_value = 1, max_value=book_data.shape[0])
        if order_selection == 'Top':
            author_0 = book_data.groupby('Author')['Number of Reviews'].mean().sort_values(ascending = False).head(n)
            # author_1 = book_data.groupby('Author')['Reading Time (min)'].mean().sort_values(ascending = False).head(n)
        else:
            author_0 = book_data.groupby('Author')['Number of Reviews'].mean().sort_values(ascending = False).tail(n)
            # author_1 = book_data.groupby('Author')['Reading Time (min)'].mean().sort_values(ascending = False).tail(n)
        
        
        # df1 = pd.pivot_table(data = book_data, index = 'Author', values = ['Number of Reviews', 'Reading Time (min)', 'Rating'], aggfunc = 'mean').reset_index()
        df1 = pd.pivot_table(data = book_data, index = 'Author', values = ['Number of Reviews', 'Reading Time (min)', 'Rating'], aggfunc = 'mean').reset_index()
        df2 = book_data.Author.value_counts()
        df3 = pd.merge(df1, right = df2, on = 'Author')
        if order_selection == 'Top':
            df = df3.sort_values(by = 'Number of Reviews',ascending = False).head(n)
        else:
            df = df3.sort_values(by = 'Number of Reviews',ascending = False).tail(n)
        
        
        f1, f2 = st.columns(2)
        with f1:
            # st.bar_chart(author_0, y = 'Number of Reviews', horizontal = True,x_label='Average Reviews')
            # st.bar_chart(df, y = 'Rating', x = 'Author', horizontal = True)
            st.bar_chart(author_0, y = 'Number of Reviews', x_label='Average Reviews')
            st.bar_chart(df, y = 'Rating', x = 'Author', x_label='Average Ratings')
        
        with f2:
            # st.bar_chart(author_1, y = 'Reading Time (min)', horizontal = True, x_label='Average reading Time')
            # st.bar_chart(df, y = 'count', x = 'Author', horizontal=True, x_label='Number of Books')
            # st.bar_chart(df, y = 'Reading Time (min)', x = 'Author', horizontal=True)
            st.bar_chart(df, y = 'count', x = 'Author', x_label='Number of Books')
            st.bar_chart(df, y = 'Reading Time (min)', x = 'Author', x_label='Average Reading Times')
            
            
        # st.bar_chart(data = df, y = ['Number of Reviews', 'Reading Time (min)'], x = 'Author', stack=False, horizontal = False)
        # st.scatter_chart(data = df, x = 'Reading Time (min)', y = 'Number of Reviews')
    else:
        st.scatter_chart(data = book_data, x = 'Reading Time (min)', y = 'Number of Reviews')
        st.scatter_chart(data = book_data, y = 'Rating', x = 'Number of Reviews')
        st.scatter_chart(data = book_data, y = 'Price', x = 'Number of Reviews')
with tab3:
    st.subheader('About the App')
    bullets = '''
    <ul>
        <li>The app takes the book <b><i>name/author/genre </i></b> of interest as input. You need to write this in the search
                box. If there is no input, it will show all the available books in the batabse. </li>
        <li>You have the level of recomendation for your selection namely: <b><i>Gener, Global</i></b> </li>
            <ul>
            <li>The <b>Genre</b> will recomend you the books falling in the same genre and around it. </li>
            <li>The <b>Global</b> method will recomend you the books in global databse context. </li>
            </ul>
        <li>The app allows you to select the books under search result and will recomend you according to to you selection
        of level of recomendation.</li>
        <li>On the second level of recomendation, the app will give you the books available in the database by the same author.</li>
        <li>The <b>SUMMARY</b> page is showing the different visuals for the distribution of Author, Genre, Rating, Price and Reading time.</li>
                '''
    st.write('Hey There :wave:')
    st.write(''' Thanks for visiting the app. The app is a part of my learning journey of DATA SCIENCE and is to demonstrate the use of
             clustering. 
             ''')
    st.markdown('''**How to Use**  ''')
    st.markdown(bullets, unsafe_allow_html=True )
    email = 'com2aftab@gmail.com'
    st.write(f'Please share your beedback @: {email}')

